### ISSUE TITLE
Playing a lot of sounds concurrently or playing sounds and using TTS concurrently can cause LineUnavaibleException

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#177]
To dupe this for testing:

```
    for (int i = 0; i < 1000; i++) {
        TextToSpeech.say("WHAT WHAT");
        TrainingProtocolBase.playSound("sounds/metal_clang.wav");
    }
```

This is a problem because after this exception occurs, no more sounds happen via playSound or via TTS.say.

Stack traces for playSound and TTS respectively:

javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
    at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
    at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
    at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
    at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
    at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1175)
    at com.shootoff.plugins.TrainingProtocolBase.playSound(TrainingProtocolBase.java:229)
    at com.shootoff.plugins.TrainingProtocolBase.playSound(TrainingProtocolBase.java:213)

javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
    at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
    at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
    at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:153)
    at marytts.util.data.audio.AudioPlayer.run(AudioPlayer.java:193)

**Comment by phrack** [comment]
The playSound is always the culprit. When playSound starts causing exceptions TTS will start getting them too.
