### ISSUE TITLE
Exception if calibration target moved all the way left off feed.

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#245]
Probably shouldn't even be able to move it off the feed.

Exception in thread "Thread-9" java.awt.image.RasterFormatException: parentX lies outside raster
    at java.awt.image.WritableRaster.createWritableChild(WritableRaster.java:222)
    at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
    at com.shootoff.camera.ShotDetection.ShotDetectionManager.processFrame(ShotDetectionManager.java:239)
    at com.shootoff.camera.CameraManager$Detector.processFrame(CameraManager.java:491)
    at com.shootoff.camera.CameraManager$Detector.streamCameraFrames(CameraManager.java:436)
    at com.shootoff.camera.CameraManager$Detector.run(CameraManager.java:367)
    at java.lang.Thread.run(Thread.java:745)

**Comment by phrack** [comment]
Still possible to move out of bounds but resizing with the mouse.
