### ISSUE TITLE
Implement initial run warning and error reporting

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#251]
Add popup on first run that tells people to make sure they have unloaded their gun and they we exclaim liability and warranty. Have check box to opt-out of error reporting. Add error reporting to automatically collector exception reports and such.

http://stackoverflow.com/questions/202345/automatic-java-error-reporting-systems

**Comment by phrack** [comment]
Looks like best option:

http://stackhunter.com/

Another alternative:

https://github.com/abrt/abrt

**Comment by phrack** [comment]
Another option: https://docs.getsentry.com/on-premise/

**Comment by phrack** [comment]
Picked Sentry and installed it on our server. Still need to do the following:
- (DONE) Remove slf4j from build.gradle and replace it with logback-classic and logback-core
- (DONE) Replace setDebug code with     ch.qos.logback.classic.Logger root = (ch.qos.logback.classic.Logger) org.slf4j.LoggerFactory.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME);
  root.setLevel(Level.DEBUG);
  - (DONE) Disable sentry in debug mode
- (DONE) Add logback.xml to classpath to be included in jar with default log level warn
- (DONE) Find catches and add logger.error(message, exception)
- (DONE) Find additional places to put logger.error(message, exception)
- (DONE) Add popup to disclaim liability and opt out of error reporting
  - (DONE) Persist error reporting setting
  - (DONE) Only show message once
- (DONE) Add note to wiki that error reporting is disabled in debug mode (link to page) and change trace instructions
- (DONE) Add error reporting wiki page that shows what we see
- (DONE) Test with no connecion
- (DONE) Clean up sentry db

**Comment by phrack** [comment]
This is an example message from when there is no connection but we try to log an error (ShootOFF carries on with no problems):

2015-10-24 11:07:57 [raven-pool-1-thread-1] WARN  n.k.r.connection.AbstractConnection - An exception due to the connection occurred, a lockdown will be initiated.
net.kencochrane.raven.connection.ConnectionException: An exception occurred while submitting the event to the sentry server.
    at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:131) ~[raven-6.0.0.jar:na]
    at net.kencochrane.raven.connection.AbstractConnection.send(AbstractConnection.java:78) ~[raven-6.0.0.jar:na]
    at net.kencochrane.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:137) [raven-6.0.0.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.net.UnknownHostException: dev.shootoffapp.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_60]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_60]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_60]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_60]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_60]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_60]
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_60]
    at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_60]
    at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168) ~[na:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_60]
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932) ~[na:1.8.0_60]
    at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:120) ~[raven-6.0.0.jar:na]
    ... 5 common frames omitted
2015-10-24 11:07:57 [raven-pool-1-thread-1] WARN  n.k.r.connection.AbstractConnection - Lockdown started for 10ms.
2015-10-24 11:07:57 [raven-pool-1-thread-1] WARN  n.k.r.connection.AbstractConnection - Lockdown ended.
