### ISSUE TITLE
Exception if calibration option changed to cropfeed during calibration

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#304]
Don't know how we didn't notice this sooner.

Exception in thread "Thread-11" java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at com.shootoff.camera.CameraManager$Detector.streamCameraFrames(CameraManager.java:518)
    at com.shootoff.camera.CameraManager$Detector.run(CameraManager.java:416)
    at java.lang.Thread.run(Thread.java:745)

**Comment by phrack** [comment]
What set of code is this from? It doesn't line up with master or the ResolutionFix branch, so I can only guess at the problem/cause.

**Comment by cbdmaul** [comment]
Good point. I'll get a better exception for it

**Comment by cbdmaul** [comment]
Nevermind, I thought I had only changed debugging lines in cameraManager but I changed something else.  I'm closing this.
