### ISSUE TITLE
Tests failing, java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#395]
java.lang.NoClassDefFoundError: Could not initialize class javafx.scene.control.Label
    at com.shootoff.plugins.ProjectorTrainingExerciseBase.<init>(ProjectorTrainingExerciseBase.java:51)
    at com.shootoff.plugins.SteelChallenge.<init>(SteelChallenge.java:41)
    at com.shootoff.plugins.TestSteelChallenge.setUp(TestSteelChallenge.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at com.shootoff.gui.JavaFXThreadingRule$OnJFXThreadStatement$1.run(JavaFXThreadingRule.java:68)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$56/1225117424.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$55/146305349.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
    at com.sun.glass.ui.win.WinApplication$$Lambda$45/776456953.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

**Comment by phrack** [comment]
This is an identical stack trace to #394.
