### ISSUE TITLE
Sometimes get an NPE when processing bright pixels

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#401]
Exception in thread "ShotDetector" java.lang.NullPointerException
    at com.shootoff.camera.shotdetection.ShotDetectionManager.processFrame(ShotDetectionManager.java:285)
    at com.shootoff.camera.CameraManager.processFrame(CameraManager.java:555)
    at com.shootoff.camera.CameraManager.streamCameraFrames(CameraManager.java:458)
    at com.shootoff.camera.CameraManager.access$0(CameraManager.java:436)
    at com.shootoff.camera.CameraManager$Detector.run(CameraManager.java:431)
    at java.lang.Thread.run(Thread.java:745)

**Comment by phrack** [comment]
I dumped the data and pixel is null for some reason.
