### ISSUE TITLE
Race condition in processFrame

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#463]
Exception in thread "ShotDetector" java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at com.shootoff.camera.CameraManager.processFrame(CameraManager.java:551)
    at com.shootoff.camera.CameraManager.streamCameraFrames(CameraManager.java:485)
    at com.shootoff.camera.CameraManager.access$0(CameraManager.java:462)
    at com.shootoff.camera.CameraManager$VideoStreamer.run(CameraManager.java:457)
    at java.lang.Thread.run(Thread.java:745)

**Comment by phrack** [comment]
Wow, that looks like one in a billion. You must have been recalibrating or closed the arena?

**Comment by cbdmaul** [comment]
recalibrating

**Comment by cbdmaul** [comment]
I have had this more than once btw.  But probably would never happen in regular user use.

**Comment by phrack** [comment]
I can try it later, but it seems plausible to me that locking on projectionBounds isn't a big deal both because the critical sections would be small and because very little code touches it anyway. In other words, in this case locking shouldn't kill performance
