### ISSUE TITLE
IndexOutOfBoundsException on CameraFactory.getWebcams

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#537]
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at java.util.Collections$SynchronizedList.get(Collections.java:2417)
    at com.shootoff.camera.CameraFactory.getWebcams(CameraFactory.java:128)

**Comment by phrack** [comment]
@cbdmaul The only camera I had open when this happened was the default. It was very strange (race condition?). Maybe the default wasn't added to the open camera list? In any case, I'd have a hell of a time reproducing it due to how seemingly random it was. Could close as unreproducable if there isn't a way to make the code safer.
